export const memberOfFamily = [
  {
    key: '1',
    english: 'Mother',
    pronunciation: '[ˈmʌðə]',
    russian: 'Мама',
  },
  {
    key: '2',
    english: 'Father',
    pronunciation: '[ˈfɑːðə]',
    russian: 'Отец, папа',
  },
  {
    key: '3',
    english: 'Parents',
    pronunciation: '[ˈpe(ə)rənt]',
    russian: 'Родители',
  },
  {
    key: '4',
    english: 'Sister',
    pronunciation: '[ˈsɪstə]',
    russian: 'Сестра',
  },
  {
    key: '5',
    english: 'Brother',
    pronunciation: '[ˈbrʌðə]',
    russian: 'Брат',
  },
  {
    key: '6',
    english: 'Siblings',
    pronunciation: '[ˈsɪblɪŋz]',
    russian: 'Братья и сёстры',
  },
  {
    key: '7',
    english: 'Grandmother',
    pronunciation: '[ˈɡræn(d)ˌmʌðə]',
    russian: 'Бабушка',
  },
  {
    key: '8',
    english: 'Grandfather',
    pronunciation: '[ˈɡræn(d)ˌfɑːðə]',
    russian: 'Дедушка',
  },
  {
    key: '9',
    english: 'Grandparents',
    pronunciation: '[ˈɡræn(d)ˌpe(ə)rənt]',
    russian: 'Бабушка и дедушка',
  },
  {
    key: '10',
    english: 'Daughter',
    pronunciation: '[ˈdɔːtə]',
    russian: 'Дочь',
  },
  {
    key: '11',
    english: 'Son',
    pronunciation: '[sʌn]',
    russian: 'Сын',
  },
  {
    key: '12',
    english: 'Children',
    pronunciation: '[ˈtʃɪldrən]',
    russian: 'Дети',
  },
  {
    key: '13',
    english: 'Wife',
    pronunciation: '[waɪf]',
    russian: 'Жена',
  },
  {
    key: '14',
    english: 'Husband',
    pronunciation: '[ˈhʌzbənd]',
    russian: 'Муж',
  },
  {
    key: '15',
    english: 'Spouse',
    pronunciation: '[spaʊs]',
    russian: 'Супруг/супруга',
  },
  {
    key: '16',
    english: 'Aunt',
    pronunciation: '[ɑːnt]',
    russian: 'Тётя',
  },
  {
    key: '17',
    english: 'Uncle',
    pronunciation: '[ˈʌŋkl]',
    russian: 'Дядя',
  },
  {
    key: '18',
    english: 'Cousin',
    pronunciation: '[ˈkʌzn]',
    russian: 'Двоюродный брат/сестра',
  },
  {
    key: '19',
    english: 'Nephew',
    pronunciation: '[ˈnefjuː]',
    russian: 'Племянник',
  },
  {
    key: '20',
    english: 'Niece',
    pronunciation: '[niːs]',
    russian: 'Племянница',
  },
  {
    key: '21',
    english: 'Granddaughter',
    pronunciation: '[ˈɡræn(d)ˌdɔːtə]',
    russian: 'Внучка',
  },
  {
    key: '22',
    english: 'Grandson',
    pronunciation: '[ˈɡræn(d)sʌn]',
    russian: 'Внук',
  },
  {
    key: '23',
    english: 'Relatives',
    pronunciation: '[ˈrelətɪvz]',
    russian: 'Родственники',
  },
  {
    key: '24',
    english: 'Family',
    pronunciation: '[ˈfæməli]',
    russian: 'Семья',
  },
];

export const appearance = [
  {
    key: '1',
    english: 'Tall',
    pronunciation: '[tɔːl]',
    russian: 'Высокий',
  },
  {
    key: '2',
    english: 'Short',
    pronunciation: '[ʃɔːt]',
    russian: 'Низкий; короткий',
  },
  {
    key: '3',
    english: 'Thin',
    pronunciation: '[θɪn]',
    russian: 'Тонкий, худой',
  },
  {
    key: '4',
    english: 'Fat',
    pronunciation: '[fæt]',
    russian: 'Толстый, жирный',
  },
  {
    key: '5',
    english: 'Slim',
    pronunciation: '[slɪm]',
    russian: 'Стройный',
  },
  {
    key: '6',
    english: 'Young',
    pronunciation: '[jʌŋ]',
    russian: 'Молодой',
  },
  {
    key: '7',
    english: 'Old',
    pronunciation: '[əʊld]',
    russian: 'Старый',
  },
  {
    key: '8',
    english: 'Handsome',
    pronunciation: '[ˈhæns(ə)m]',
    russian: 'Красивый (о мужчине)',
  },
  {
    key: '9',
    english: 'Beautiful',
    pronunciation: '[ˈbjuːtɪf(ə)l]',
    russian: 'Красивый/красивая',
  },
  {
    key: '10',
    english: 'Pretty',
    pronunciation: '[ˈprɪti]',
    russian: 'Хорошенькая, симпатичная',
  },
  {
    key: '11',
    english: 'Ugly',
    pronunciation: '[ˈʌɡli]',
    russian: 'Некрасивый, уродливый',
  },
  {
    key: '12',
    english: 'Strong',
    pronunciation: '[strɒŋ]',
    russian: 'Сильный',
  },
  {
    key: '13',
    english: 'Weak',
    pronunciation: '[wiːk]',
    russian: 'Слабый',
  },
  {
    key: '14',
    english: 'Long (hair)',
    pronunciation: '[lɒŋ]',
    russian: 'Длинный (о волосах)',
  },
  {
    key: '15',
    english: 'Short (hair)',
    pronunciation: '[ʃɔːt]',
    russian: 'Короткий (о волосах)',
  },
  {
    key: '16',
    english: 'Curly (hair)',
    pronunciation: '[ˈkɜːli]',
    russian: 'Кудрявый (о волосах)',
  },
  {
    key: '17',
    english: 'Straight (hair)',
    pronunciation: '[streɪt]',
    russian: 'Прямой (о волосах)',
  },
  {
    key: '18',
    english: 'Dark (hair)',
    pronunciation: '[dɑːk]',
    russian: 'Тёмный (о волосах)',
  },
  {
    key: '19',
    english: 'Fair (hair)',
    pronunciation: '[feə]',
    russian: 'Светлый (о волосах)',
  },
  {
    key: '20',
    english: 'Blonde (hair)',
    pronunciation: '[blɒnd]',
    russian: 'Блондинистый',
  },
  {
    key: '21',
    english: 'Brown (hair)',
    pronunciation: '[braʊn]',
    russian: 'Каштановый (о волосах)',
  },
  {
    key: '22',
    english: 'Red (hair)',
    pronunciation: '[red]',
    russian: 'Рыжий (о волосах)',
  },
  {
    key: '23',
    english: 'Bald',
    pronunciation: '[bɔːld]',
    russian: 'Лысый',
  },
  {
    key: '24',
    english: 'Blue (eyes)',
    pronunciation: '[bluː]',
    russian: 'Голубые (глаза)',
  },
  {
    key: '25',
    english: 'Brown (eyes)',
    pronunciation: '[braʊn]',
    russian: 'Карие (глаза)',
  },
  {
    key: '26',
    english: 'Green (eyes)',
    pronunciation: '[ɡriːn]',
    russian: 'Зелёные (глаза)',
  },
  {
    key: '27',
    english: 'Big (eyes)',
    pronunciation: '[bɪɡ]',
    russian: 'Большие (глаза)',
  },
  {
    key: '28',
    english: 'Small (eyes)',
    pronunciation: '[smɔːl]',
    russian: 'Маленькие (глаза)',
  },
  {
    key: '29',
    english: 'Beard',
    pronunciation: '[bɪəd]',
    russian: 'Борода',
  },
  {
    key: '30',
    english: 'Moustache',
    pronunciation: '[məˈstɑːʃ]',
    russian: 'Усы',
  },
  {
    key: '31',
    english: 'Glasses',
    pronunciation: '[ˈɡlɑːsɪz]',
    russian: 'Очки',
  },
];

export const character = [
  {
    key: '1',
    english: 'Kind',
    pronunciation: '[kaɪnd]',
    russian: 'Добрый',
  },
  {
    key: '2',
    english: 'Nice',
    pronunciation: '[naɪs]',
    russian: 'Хороший, приятный',
  },
  {
    key: '3',
    english: 'Friendly',
    pronunciation: '[ˈfren(d)li]',
    russian: 'Дружелюбный',
  },
  {
    key: '4',
    english: 'Funny',
    pronunciation: '[ˈfʌni]',
    russian: 'Смешной',
  },
  {
    key: '5',
    english: 'Serious',
    pronunciation: '[ˈsɪəriəs]',
    russian: 'Серьёзный',
  },
  {
    key: '6',
    english: 'Quiet',
    pronunciation: '[ˈkwaɪət]',
    russian: 'Тихий, спокойный',
  },
  {
    key: '7',
    english: 'Shy',
    pronunciation: '[ʃaɪ]',
    russian: 'Стеснительный',
  },
  {
    key: '8',
    english: 'Smart / Clever',
    pronunciation: '[smɑːt] / [ˈklevə]',
    russian: 'Умный',
  },
  {
    key: '9',
    english: 'Stupid',
    pronunciation: '[ˈstjuːpɪd]',
    russian: 'Глупый',
  },
  {
    key: '10',
    english: 'Lazy',
    pronunciation: '[ˈleɪzi]',
    russian: 'Ленивый',
  },
  {
    key: '11',
    english: 'Hard-working',
    pronunciation: '[ˌhɑːd ˈwɜːkɪŋ]',
    russian: 'Трудолюбивый',
  },
  {
    key: '12',
    english: 'Helpful',
    pronunciation: '[ˈhelpf(ə)l]',
    russian: 'Полезный, готовый помочь',
  },
  {
    key: '13',
    english: 'Polite',
    pronunciation: '[pəˈlaɪt]',
    russian: 'Вежливый',
  },
  {
    key: '14',
    english: 'Rude',
    pronunciation: '[ruːd]',
    russian: 'Грубый',
  },
  {
    key: '15',
    english: 'Patient',
    pronunciation: '[ˈpeɪʃ(ə)nt]',
    russian: 'Терпеливый',
  },
  {
    key: '16',
    english: 'Honest',
    pronunciation: '[ˈɒnɪst]',
    russian: 'Честный',
  },
  {
    key: '17',
    english: 'Cheerful',
    pronunciation: '[ˈtʃɪəf(ə)l]',
    russian: 'Весёлый, жизнерадостный',
  },
  {
    key: '18',
    english: 'Sad',
    pronunciation: '[sæd]',
    russian: 'Грустный',
  },
  {
    key: '19',
    english: 'Angry',
    pronunciation: '[ˈæŋɡri]',
    russian: 'Злой, сердитый',
  },
  {
    key: '20',
    english: 'Calm',
    pronunciation: '[kɑːm]',
    russian: 'Спокойный',
  },
  {
    key: '21',
    english: 'Nervous',
    pronunciation: '[ˈnɜːvəs]',
    russian: 'Нервный',
  },
  {
    key: '22',
    english: 'Boring',
    pronunciation: '[ˈbɔːrɪŋ]',
    russian: 'Скучный',
  },
  {
    key: '23',
    english: 'Interesting',
    pronunciation: '[ˈɪntrəstɪŋ]',
    russian: 'Интересный',
  },
  {
    key: '24',
    english: 'In a good mood',
    pronunciation: '[ɪn ə ɡʊd muːd]',
    russian: 'В хорошем настроении',
  },
  {
    key: '25',
    english: 'In a bad mood',
    pronunciation: '[ɪn ə bæd muːd]',
    russian: 'В плохом настроении',
  },
];
