export const animals = [
  { key: '1', english: 'Dog', pronunciation: '[dɒɡ]', russian: 'Собака' },
  { key: '2', english: 'Cat', pronunciation: '[kæt]', russian: 'Кошка' },
  { key: '3', english: 'Bird', pronunciation: '[bɜːd]', russian: 'Птица' },
  { key: '4', english: 'Fish', pronunciation: '[fɪʃ]', russian: 'Рыба' },
  { key: '5', english: 'Rabbit', pronunciation: '[ˈræbɪt]', russian: 'Кролик' },
  { key: '6', english: 'Hamster', pronunciation: '[ˈhæmstə]', russian: 'Хомяк' },
  { key: '7', english: 'Parrot', pronunciation: '[ˈpærət]', russian: 'Попугай' },
  { key: '8', english: 'Horse', pronunciation: '[hɔːs]', russian: 'Лошадь' },
  { key: '9', english: 'Cow', pronunciation: '[kaʊ]', russian: 'Корова' },
  { key: '10', english: 'Pig', pronunciation: '[pɪɡ]', russian: 'Свинья' },
  { key: '11', english: 'Sheep', pronunciation: '[ʃiːp]', russian: 'Овца' },
  { key: '12', english: 'Goat', pronunciation: '[ɡəʊt]', russian: 'Коза' },
  { key: '13', english: 'Chicken', pronunciation: '[ˈtʃɪkɪn]', russian: 'Курица' },
  { key: '14', english: 'Duck', pronunciation: '[dʌk]', russian: 'Утка' },
  { key: '15', english: 'Lion', pronunciation: '[ˈlaɪən]', russian: 'Лев' },
  { key: '16', english: 'Tiger', pronunciation: '[ˈtaɪɡə]', russian: 'Тигр' },
  { key: '17', english: 'Elephant', pronunciation: '[ˈelɪfənt]', russian: 'Слон' },
  { key: '18', english: 'Monkey', pronunciation: '[ˈmʌŋki]', russian: 'Обезьяна' },
  { key: '19', english: 'Bear', pronunciation: '[beə]', russian: 'Медведь' },
  { key: '20', english: 'Wolf', pronunciation: '[wʊlf]', russian: 'Волк' },
  { key: '21', english: 'Fox', pronunciation: '[fɒks]', russian: 'Лиса' },
  { key: '22', english: 'Giraffe', pronunciation: '[dʒɪˈrɑːf]', russian: 'Жираф' },
  { key: '23', english: 'Zebra', pronunciation: '[ˈzebrə]', russian: 'Зебра' },
  { key: '24', english: 'Kangaroo', pronunciation: '[ˌkæŋɡəˈruː]', russian: 'Кенгуру' },
  { key: '25', english: 'Panda', pronunciation: '[ˈpændə]', russian: 'Панда' },
  { key: '26', english: 'Snake', pronunciation: '[sneɪk]', russian: 'Змея' },
  { key: '27', english: 'Crocodile', pronunciation: '[ˈkrɒkədaɪl]', russian: 'Крокодил' },
  { key: '28', english: 'Turtle', pronunciation: '[ˈtɜːtl]', russian: 'Черепаха' },
  { key: '29', english: 'Frog', pronunciation: '[frɒɡ]', russian: 'Лягушка' },
  { key: '30', english: 'Mouse', pronunciation: '[maʊs]', russian: 'Мышь' },
  { key: '31', english: 'Rat', pronunciation: '[ræt]', russian: 'Крыса' },
  { key: '32', english: 'Deer', pronunciation: '[dɪə]', russian: 'Олень' },
  { key: '33', english: 'Shark', pronunciation: '[ʃɑːk]', russian: 'Акула' },
  { key: '34', english: 'Whale', pronunciation: '[weɪl]', russian: 'Кит' },
  { key: '35', english: 'Dolphin', pronunciation: '[ˈdɒlfɪn]', russian: 'Дельфин' },
  { key: '36', english: 'Penguin', pronunciation: '[ˈpeŋɡwɪn]', russian: 'Пингвин' },
  { key: '37', english: 'Owl', pronunciation: '[aʊl]', russian: 'Сова' },
  { key: '38', english: 'Eagle', pronunciation: '[ˈiːɡl]', russian: 'Орёл' },
  { key: '39', english: 'Butterfly', pronunciation: '[ˈbʌtəflaɪ]', russian: 'Бабочка' },
  { key: '40', english: 'Bee', pronunciation: '[biː]', russian: 'Пчела' },
  { key: '41', english: '-----', pronunciation: '-----', russian: '-----' },
  { key: '42', english: 'Body part', pronunciation: 'Body part', russian: 'Body part' },
  { key: '43', english: 'Tail', pronunciation: '[teɪl]', russian: 'Хвост' },
  { key: '44', english: 'Wing', pronunciation: '[wɪŋ]', russian: 'Крыло' },
  { key: '45', english: 'Leg', pronunciation: '[leɡ]', russian: 'Лапа / нога' },
  { key: '46', english: 'Paw', pronunciation: '[pɔː]', russian: 'Лапа' },
  { key: '47', english: 'Claw', pronunciation: '[klɔː]', russian: 'Коготь' },
  { key: '48', english: 'Beak', pronunciation: '[biːk]', russian: 'Клюв' },
  { key: '49', english: 'Teeth', pronunciation: '[tiːθ]', russian: 'Зубы' },
  { key: '50', english: 'Fur', pronunciation: '[fɜː]', russian: 'Мех' },
  { key: '51', english: 'Feathers', pronunciation: '[ˈfeðəz]', russian: 'Перья' },
  { key: '52', english: 'Horns', pronunciation: '[hɔːnz]', russian: 'Рога' },
  { key: '53', english: 'Hooves', pronunciation: '[huːvz]', russian: 'Копыта' },
  { key: '54', english: 'Tusks', pronunciation: '[tʌsks]', russian: 'Бивни' },
  { key: '55', english: 'Neck', pronunciation: '[nek]', russian: 'Шея' },
  { key: '56', english: 'Head', pronunciation: '[hed]', russian: 'Голова' },
  { key: '57', english: 'Eyes', pronunciation: '[aɪz]', russian: 'Глаза' },
];

export const animalAdjectives = [
  { key: '1', english: 'Big', pronunciation: '[bɪɡ]', russian: 'Большой' },
  { key: '2', english: 'Small', pronunciation: '[smɔːl]', russian: 'Маленький' },
  { key: '3', english: 'Fast', pronunciation: '[fɑːst]', russian: 'Быстрый' },
  { key: '4', english: 'Slow', pronunciation: '[sləʊ]', russian: 'Медленный' },
  { key: '5', english: 'Strong', pronunciation: '[strɒŋ]', russian: 'Сильный' },
  { key: '6', english: 'Dangerous', pronunciation: '[ˈdeɪndʒərəs]', russian: 'Опасный' },
  { key: '7', english: 'Friendly', pronunciation: '[ˈfrendli]', russian: 'Дружелюбный' },
  { key: '8', english: 'Wild', pronunciation: '[waɪld]', russian: 'Дикий' },
  { key: '9', english: 'Domestic', pronunciation: '[dəˈmestɪk]', russian: 'Домашний' },
  { key: '10', english: 'Clever', pronunciation: '[ˈklevə]', russian: 'Умный' },
  { key: '11', english: 'Beautiful', pronunciation: '[ˈbjuːtɪfəl]', russian: 'Красивый' },
  { key: '12', english: 'Heavy', pronunciation: '[ˈhevi]', russian: 'Тяжёлый' },
  { key: '13', english: 'Light', pronunciation: '[laɪt]', russian: 'Лёгкий' },
  { key: '14', english: 'Cute', pronunciation: '[kjuːt]', russian: 'Милый' },
  { key: '15', english: 'Scary', pronunciation: '[ˈskeəri]', russian: 'Страшный' },
  { key: '16', english: '-----', pronunciation: '-----', russian: '-----' },
  { key: '17', english: 'Run', pronunciation: '[rʌn]', russian: 'Бегать' },
  { key: '18', english: 'Jump', pronunciation: '[dʒʌmp]', russian: 'Прыгать' },
  { key: '19', english: 'Swim', pronunciation: '[swɪm]', russian: 'Плавать' },
  { key: '20', english: 'Fly', pronunciation: '[flaɪ]', russian: 'Летать' },
  { key: '21', english: 'Climb', pronunciation: '[klaɪm]', russian: 'Лазить' },
  { key: '22', english: 'Hunt', pronunciation: '[hʌnt]', russian: 'Охотиться' },
  { key: '23', english: 'Roar', pronunciation: '[rɔː]', russian: 'Рычать' },
  { key: '24', english: 'Growl', pronunciation: '[ɡraʊl]', russian: 'Рычать / ворчать' },
  { key: '25', english: 'Bark', pronunciation: '[bɑːk]', russian: 'Лаять' },
  { key: '26', english: 'Meow', pronunciation: '[miˈaʊ]', russian: 'Мяукать' },
  { key: '27', english: 'Moo', pronunciation: '[muː]', russian: 'Мычать' },
  { key: '28', english: 'Quack', pronunciation: '[kwæk]', russian: 'Крякать' },
  { key: '29', english: 'Chirp', pronunciation: '[tʃɜːp]', russian: 'Чирикать' },
  { key: '30', english: 'Hiss', pronunciation: '[hɪs]', russian: 'Шипеть' },
  { key: '31', english: 'Crawl', pronunciation: '[krɔːl]', russian: 'Ползать' },
  { key: '32', english: 'Hop', pronunciation: '[hɒp]', russian: 'Прыгать (на одной ноге/лапе)' },
  { key: '33', english: 'Gallop', pronunciation: '[ˈɡæləp]', russian: 'Скакать галопом' },
  { key: '34', english: 'Slither', pronunciation: '[ˈslɪðə]', russian: 'Скользить / извиваться (о змее)' },
  { key: '35', english: 'Swing', pronunciation: '[swɪŋ]', russian: 'Качаться (на ветках)' },
  { key: '36', english: 'Dive', pronunciation: '[daɪv]', russian: 'Нырять' },
];

export const animalEnvironment = [
  { key: '1', english: 'Forest', pronunciation: '[ˈfɒrɪst]', russian: 'Лес' },
  { key: '2', english: 'Jungle', pronunciation: '[ˈdʒʌŋɡl]', russian: 'Джунгли' },
  { key: '3', english: 'Desert', pronunciation: '[ˈdezət]', russian: 'Пустыня' },
  { key: '4', english: 'Ocean', pronunciation: '[ˈəʊʃən]', russian: 'Океан' },
  { key: '5', english: 'River', pronunciation: '[ˈrɪvə]', russian: 'Река' },
  { key: '6', english: 'Farm', pronunciation: '[fɑːm]', russian: 'Ферма' },
  { key: '7', english: 'Zoo', pronunciation: '[zuː]', russian: 'Зоопарк' },
  { key: '8', english: 'Grass', pronunciation: '[ɡrɑːs]', russian: 'Трава' },
  { key: '9', english: 'Meat', pronunciation: '[miːt]', russian: 'Мясо' },
  { key: '10', english: 'Fish', pronunciation: '[fɪʃ]', russian: 'Рыба' },
  { key: '11', english: 'Leaves', pronunciation: '[liːvz]', russian: 'Листья' },
  { key: '12', english: 'Insects', pronunciation: '[ˈɪnsekts]', russian: 'Насекомые' },
];