export const jobsAndProfessions = [
  {
    key: '1',
    english: 'Teacher',
    pronunciation: '[ˈtiːtʃə]',
    russian: 'Учитель',
  },
  {
    key: '2',
    english: 'Doctor',
    pronunciation: '[ˈdɒktə]',
    russian: 'Врач',
  },
  {
    key: '3',
    english: 'Nurse',
    pronunciation: '[nɜːs]',
    russian: 'Медсестра / Медбрат',
  },
  {
    key: '4',
    english: 'Engineer',
    pronunciation: '[ˌendʒɪˈnɪə]',
    russian: 'Инженер',
  },
  {
    key: '5',
    english: 'Lawyer',
    pronunciation: '[ˈlɔːjə]',
    russian: 'Юрист, адвокат',
  },
  {
    key: '6',
    english: 'Police officer',
    pronunciation: '[pəˈliːs ˌɒfɪsə]',
    russian: 'Полицейский',
  },
  {
    key: '7',
    english: 'Firefighter',
    pronunciation: '[ˈfaɪəfaɪtə]',
    russian: 'Пожарный',
  },
  {
    key: '8',
    english: 'Chef / Cook',
    pronunciation: '[ʃef] / [kʊk]',
    russian: 'Шеф-повар / Повар',
  },
  {
    key: '9',
    english: 'Waiter / Waitress',
    pronunciation: '[ˈweɪtə] / [ˈweɪtrəs]',
    russian: 'Официант / Официантка',
  },
  {
    key: '10',
    english: 'Driver',
    pronunciation: '[ˈdraɪvə]',
    russian: 'Водитель',
  },
  {
    key: '11',
    english: 'Builder',
    pronunciation: '[ˈbɪldə]',
    russian: 'Строитель',
  },
  {
    key: '12',
    english: 'Shop assistant',
    pronunciation: '[ˈʃɒp əˌsɪstənt]',
    russian: 'Продавец',
  },
  {
    key: '13',
    english: 'Accountant',
    pronunciation: '[əˈkaʊntənt]',
    russian: 'Бухгалтер',
  },
  {
    key: '14',
    english: 'Journalist',
    pronunciation: '[ˈdʒɜːnəlɪst]',
    russian: 'Журналист',
  },
  {
    key: '15',
    english: 'Programmer',
    pronunciation: '[ˈprəʊɡræmə]',
    russian: 'Программист',
  },
  {
    key: '16',
    english: 'Artist',
    pronunciation: '[ˈɑːtɪst]',
    russian: 'Художник',
  },
  {
    key: '17',
    english: 'Musician',
    pronunciation: '[mjuˈzɪʃ(ə)n]',
    russian: 'Музыкант',
  },
  {
    key: '18',
    english: 'Actor / Actress',
    pronunciation: '[ˈæktə] / [ˈæktrəs]',
    russian: 'Актёр / Актриса',
  },
  {
    key: '19',
    english: 'Singer',
    pronunciation: '[ˈsɪŋə]',
    russian: 'Певец / Певица',
  },
  {
    key: '20',
    english: 'Photographer',
    pronunciation: '[fəˈtɒɡrəfə]',
    russian: 'Фотограф',
  },
  {
    key: '21',
    english: 'Receptionist',
    pronunciation: '[rɪˈsepʃənɪst]',
    russian: 'Администратор (на ресепшене)',
  },
  {
    key: '22',
    english: 'Secretary',
    pronunciation: '[ˈsekrət(ə)ri]',
    russian: 'Секретарь',
  },
  {
    key: '23',
    english: 'Manager',
    pronunciation: '[ˈmænɪdʒə]',
    russian: 'Менеджер',
  },
  {
    key: '24',
    english: 'Businessman / Businesswoman',
    pronunciation: '[ˈbɪznəsmæn] / [ˈbɪznəswʊmæn]',
    russian: 'Бизнесмен / Бизнесвумен',
  },
  {
    key: '25',
    english: 'Cleaner',
    pronunciation: '[ˈkliːnə]',
    russian: 'Уборщик / Уборщица',
  },
  {
    key: '26',
    english: 'Farmer',
    pronunciation: '[ˈfɑːmə]',
    russian: 'Фермер',
  },
  {
    key: '27',
    english: 'Pilot',
    pronunciation: '[ˈpaɪlət]',
    russian: 'Пилот',
  },
  {
    key: '28',
    english: 'Flight attendant',
    pronunciation: '[ˈflaɪt əˌtendənt]',
    russian: 'Бортпроводник',
  },
  {
    key: '29',
    english: 'Hairdresser',
    pronunciation: '[ˈheədresə]',
    russian: 'Парикмахер',
  },
  {
    key: '30',
    english: 'Vet',
    pronunciation: '[vet]',
    russian: 'Ветеринар',
  },
];

export const workplaces = [
  {
    key: '1',
    english: 'Office',
    pronunciation: '[ˈɒfɪs]',
    russian: 'Офис',
  },
  {
    key: '2',
    english: 'School',
    pronunciation: '[skuːl]',
    russian: 'Школа',
  },
  {
    key: '3',
    english: 'University',
    pronunciation: '[ˌjuːnɪˈvɜːsəti]',
    russian: 'Университет',
  },
  {
    key: '4',
    english: 'Hospital',
    pronunciation: '[ˈhɒspɪt(ə)l]',
    russian: 'Больница',
  },
  {
    key: '5',
    english: 'Restaurant',
    pronunciation: '[ˈrestrɒnt]',
    russian: 'Ресторан',
  },
  {
    key: '6',
    english: 'Cafe',
    pronunciation: '[ˈkæfeɪ]',
    russian: 'Кафе',
  },
  {
    key: '7',
    english: 'Hotel',
    pronunciation: '[həʊˈtel]',
    russian: 'Отель',
  },
  {
    key: '8',
    english: 'Shop / Store',
    pronunciation: '[ʃɒp] / [stɔː]',
    russian: 'Магазин',
  },
  {
    key: '9',
    english: 'Supermarket',
    pronunciation: '[ˈsuːpəmɑːkɪt]',
    russian: 'Супермаркет',
  },
  {
    key: '10',
    english: 'Factory',
    pronunciation: '[ˈfækt(ə)ri]',
    russian: 'Фабрика, завод',
  },
  {
    key: '11',
    english: 'Bank',
    pronunciation: '[bæŋk]',
    russian: 'Банк',
  },
  {
    key: '12',
    english: 'Police station',
    pronunciation: '[pəˈliːs ˌsteɪʃ(ə)n]',
    russian: 'Полицейский участок',
  },
  {
    key: '13',
    english: 'Fire station',
    pronunciation: '[ˈfaɪə ˌsteɪʃ(ə)n]',
    russian: 'Пожарная часть',
  },
  {
    key: '14',
    english: 'Construction site',
    pronunciation: '[kənˈstrʌkʃ(ə)n saɪt]',
    russian: 'Строительная площадка',
  },
  {
    key: '15',
    english: 'Farm',
    pronunciation: '[fɑːm]',
    russian: 'Ферма',
  },
  {
    key: '16',
    english: 'Airport',
    pronunciation: '[ˈeəpɔːt]',
    russian: 'Аэропорт',
  },
  {
    key: '17',
    english: 'Studio',
    pronunciation: '[ˈstjuːdiəʊ]',
    russian: 'Студия',
  },
  {
    key: '18',
    english: 'Theatre',
    pronunciation: '[ˈθɪətə]',
    russian: 'Театр',
  },
  {
    key: '19',
    english: 'Hospitality (industry)',
    pronunciation: '[ˌhɒspɪˈtæləti]',
    russian: 'Сфера гостеприимства',
  },
  {
    key: '20',
    english: 'Laboratory',
    pronunciation: '[ləˈbɒrət(ə)ri]',
    russian: 'Лаборатория',
  },
  {
    key: '21',
    english: 'Court',
    pronunciation: '[kɔːt]',
    russian: 'Суд',
  },
  {
    key: '22',
    english: 'School (as a workplace)',
    pronunciation: '[skuːl]',
    russian: 'Школа (как место работы)',
  },
  {
    key: '23',
    english: 'Salon (beauty)',
    pronunciation: '[ˈsælɒn]',
    russian: 'Салон (красоты)',
  },
  {
    key: '24',
    english: 'Garage',
    pronunciation: '[ˈɡærɑːʒ]',
    russian: 'Гараж, автосервис',
  },
  {
    key: '25',
    english: 'Office building',
    pronunciation: '[ˈɒfɪs ˌbɪldɪŋ]',
    russian: 'Офисное здание',
  },
];

export const jobRelatedVerbsAndPhrases = [
  {
    key: '1',
    english: 'Work',
    pronunciation: '[wɜːk]',
    russian: 'Работать',
  },
  {
    key: '2',
    english: 'Work as (a teacher)',
    pronunciation: '[wɜːk æz]',
    russian: 'Работать (кем-то)',
  },
  {
    key: '3',
    english: 'Work in (an office)',
    pronunciation: '[wɜːk ɪn]',
    russian: 'Работать (где-то / в сфере)',
  },
  {
    key: '4',
    english: 'Work for (a company)',
    pronunciation: '[wɜːk fɔː]',
    russian: 'Работать на (компанию)',
  },
  {
    key: '5',
    english: 'Work from home',
    pronunciation: '[wɜːk frəm həʊm]',
    russian: 'Работать из дома',
  },
  {
    key: '6',
    english: 'Full-time job',
    pronunciation: '[ˌfʊl ˈtaɪm dʒɒb]',
    russian: 'Полная занятость',
  },
  {
    key: '7',
    english: 'Part-time job',
    pronunciation: '[ˌpɑːt ˈtaɪm dʒɒb]',
    russian: 'Частичная занятость',
  },
  {
    key: '8',
    english: 'Start work (at 9 am)',
    pronunciation: '[stɑːt wɜːk]',
    russian: 'Начинать работу (в 9 утра)',
  },
  {
    key: '9',
    english: 'Finish work (at 6 pm)',
    pronunciation: '[ˈfɪnɪʃ wɜːk]',
    russian: 'Заканчивать работу (в 6 вечера)',
  },
  {
    key: '10',
    english: 'Have a break / lunch break',
    pronunciation: '[hæv ə breɪk] / [ˈlʌntʃ breɪk]',
    russian: 'Иметь перерыв / обеденный перерыв',
  },
  {
    key: '11',
    english: 'Earn money',
    pronunciation: '[ɜːn ˈmʌni]',
    russian: 'Зарабатывать деньги',
  },
  {
    key: '12',
    english: 'Get a salary',
    pronunciation: '[ɡet ə ˈsæləri]',
    russian: 'Получать зарплату',
  },
  {
    key: '13',
    english: 'Help people',
    pronunciation: '[help ˈpiːp(ə)l]',
    russian: 'Помогать людям',
  },
  {
    key: '14',
    english: 'Work with people',
    pronunciation: '[wɜːk wɪð ˈpiːp(ə)l]',
    russian: 'Работать с людьми',
  },
  {
    key: '15',
    english: 'Work with computers',
    pronunciation: '[wɜːk wɪð kəmˈpjuːtəz]',
    russian: 'Работать с компьютерами',
  },
  {
    key: '16',
    english: 'Work outdoors',
    pronunciation: '[wɜːk ˌaʊtˈdɔːz]',
    russian: 'Работать на улице',
  },
  {
    key: '17',
    english: 'Work indoors',
    pronunciation: '[wɜːk ˌɪnˈdɔːz]',
    russian: 'Работать в помещении',
  },
  {
    key: '18',
    english: 'Be responsible for',
    pronunciation: '[bi rɪˈspɒnsəb(ə)l fɔː]',
    russian: 'Быть ответственным за',
  },
  {
    key: '19',
    english: 'Take care of (patients)',
    pronunciation: '[teɪk keər ɒv]',
    russian: 'Заботиться о (пациентах)',
  },
  {
    key: '20',
    english: 'Deal with (customers)',
    pronunciation: '[diːl wɪð]',
    russian: 'Иметь дело с (клиентами)',
  },
  {
    key: '21',
    english: 'Answer phone calls',
    pronunciation: '[ˈɑːnsə fəʊn kɔːlz]',
    russian: 'Отвечать на звонки',
  },
  {
    key: '22',
    english: 'Write emails',
    pronunciation: '[raɪt ˈiːmeɪlz]',
    russian: 'Писать письма (электронные)',
  },
  {
    key: '23',
    english: 'Meet clients',
    pronunciation: '[miːt ˈklaɪənts]',
    russian: 'Встречаться с клиентами',
  },
  {
    key: '24',
    english: 'Drive a car / bus / taxi',
    pronunciation: '[draɪv ə kɑː]',
    russian: 'Водить машину / автобус / такси',
  },
  {
    key: '25',
    english: 'Build houses',
    pronunciation: '[bɪld ˈhaʊzɪz]',
    russian: 'Строить дома',
  },
  {
    key: '26',
    english: 'Teach students',
    pronunciation: '[tiːtʃ ˈstjuːd(ə)nts]',
    russian: 'Учить студентов',
  },
  {
    key: '27',
    english: 'Cook food',
    pronunciation: '[kʊk fuːd]',
    russian: 'Готовить еду',
  },
  {
    key: '28',
    english: 'Serve customers',
    pronunciation: '[sɜːv ˈkʌstəməz]',
    russian: 'Обслуживать клиентов',
  },
  {
    key: '29',
    english: 'Design (websites / clothes)',
    pronunciation: '[dɪˈzaɪn]',
    russian: 'Разрабатывать, создавать дизайн',
  },
  {
    key: '30',
    english: 'Look after (children / animals)',
    pronunciation: '[lʊk ˈɑːftə]',
    russian: 'Присматривать за (детьми / животными)',
  },
];
