export const fearsAndPhobias = [
  // BASIC FEARS (ОСНОВНЫЕ СТРАХИ)
  { key: '1', english: 'Spider', pronunciation: '[ˈspaɪdə]', russian: 'Паук' },
  { key: '2', english: 'Snake', pronunciation: '[sneɪk]', russian: 'Змея' },
  { key: '3', english: 'Dog', pronunciation: '[dɒɡ]', russian: 'Собака' },
  { key: '4', english: 'Dark', pronunciation: '[dɑːk]', russian: 'Темнота' },
  { key: '5', english: 'Heights', pronunciation: '[haɪts]', russian: 'Высота' },
  { key: '6', english: 'Flying', pronunciation: '[ˈflaɪɪŋ]', russian: 'Полеты (на самолете)' },
  { key: '7', english: 'Thunder', pronunciation: '[ˈθʌndə]', russian: 'Гром' },
  { key: '8', english: 'Lightning', pronunciation: '[ˈlaɪtnɪŋ]', russian: 'Молния' },
  { key: '9', english: 'Needle', pronunciation: '[ˈniːdl]', russian: 'Игла (укол)' },
  { key: '10', english: 'Dentist', pronunciation: '[ˈdentɪst]', russian: 'Стоматолог' },
  { key: '11', english: 'Mouse', pronunciation: '[maʊs]', russian: 'Мышь' },
  { key: '12', english: 'Insect', pronunciation: '[ˈɪnsekt]', russian: 'Насекомое' },
  { key: '13', english: 'Clown', pronunciation: '[klaʊn]', russian: 'Клоун' },
  { key: '14', english: 'Ghost', pronunciation: '[ɡəʊst]', russian: 'Привидение' },
  { key: '15', english: 'Stranger', pronunciation: '[ˈstreɪndʒə]', russian: 'Незнакомец' },
  { key: '16', english: 'Exam', pronunciation: '[ɪɡˈzæm]', russian: 'Экзамен' },
  { key: '17', english: 'Public speaking', pronunciation: '[ˈpʌblɪk ˈspiːkɪŋ]', russian: 'Публичное выступление' },
  { key: '18', english: 'Water', pronunciation: '[ˈwɔːtə]', russian: 'Вода' },
  { key: '19', english: 'Crowd', pronunciation: '[kraʊd]', russian: 'Толпа' },
  { key: '20', english: 'Confined space', pronunciation: '[kənˈfaɪnd speɪs]', russian: 'Закрытое пространство' },
  { key: '21', english: '-----', pronunciation: '-----', russian: '-----' },
  
  // FEELINGS (ЧУВСТВА И ЭМОЦИИ)
  { key: '22', english: 'Feelings', pronunciation: 'Feelings', russian: 'Чувства' },
  { key: '23', english: 'Afraid', pronunciation: '[əˈfreɪd]', russian: 'Испуганный' },
  { key: '24', english: 'Scared', pronunciation: '[skeəd]', russian: 'Напуганный' },
  { key: '25', english: 'Terrified', pronunciation: '[ˈterɪfaɪd]', russian: 'В ужасе' },
  { key: '26', english: 'Frightened', pronunciation: '[ˈfraɪtnd]', russian: 'Испуганный' },
  { key: '27', english: 'Nervous', pronunciation: '[ˈnɜːvəs]', russian: 'Нервный' },
  { key: '28', english: 'Anxious', pronunciation: '[ˈæŋkʃəs]', russian: 'Встревоженный' },
  { key: '29', english: 'Worried', pronunciation: '[ˈwʌrid]', russian: 'Беспокоящийся' },
  { key: '30', english: 'Panic', pronunciation: '[ˈpænɪk]', russian: 'Паника' },
  { key: '31', english: 'Fear', pronunciation: '[fɪə]', russian: 'Страх' },
  { key: '32', english: 'Phobia', pronunciation: '[ˈfəʊbiə]', russian: 'Фобия' },
  { key: '33', english: '-----', pronunciation: '-----', russian: '-----' },
  
  // VERBS (ГЛАГОЛЫ)
  { key: '34', english: 'Verbs', pronunciation: 'Verbs', russian: 'Глаголы' },
  { key: '35', english: 'Fear', pronunciation: '[fɪə]', russian: 'Бояться' },
  { key: '36', english: 'Scream', pronunciation: '[skriːm]', russian: 'Кричать (от страха)' },
  { key: '37', english: 'Shake', pronunciation: '[ʃeɪk]', russian: 'Дрожать' },
  { key: '38', english: 'Tremble', pronunciation: '[ˈtrembl]', russian: 'Трястись' },
  { key: '39', english: 'Hide', pronunciation: '[haɪd]', russian: 'Прятаться' },
  { key: '40', english: 'Run away', pronunciation: '[rʌn əˈweɪ]', russian: 'Убегать' },
  { key: '41', english: 'Avoid', pronunciation: '[əˈvɔɪd]', russian: 'Избегать' },
  { key: '42', english: 'Bite', pronunciation: '[baɪt]', russian: 'Кусать' },
  { key: '43', english: 'Chase', pronunciation: '[tʃeɪs]', russian: 'Преследовать' },
  { key: '44', english: 'Attack', pronunciation: '[əˈtæk]', russian: 'Атаковать' },
  { key: '45', english: '-----', pronunciation: '-----', russian: '-----' },
  
  // ADJECTIVES (ПРИЛАГАТЕЛЬНЫЕ)
  { key: '46', english: 'Adjectives', pronunciation: 'Adjectives', russian: 'Прилагательные' },
  { key: '47', english: 'Scary', pronunciation: '[ˈskeəri]', russian: 'Страшный' },
  { key: '48', english: 'Frightening', pronunciation: '[ˈfraɪtnɪŋ]', russian: 'Пугающий' },
  { key: '49', english: 'Terrifying', pronunciation: '[ˈterɪfaɪɪŋ]', russian: 'Ужасающий' },
  { key: '50', english: 'Dangerous', pronunciation: '[ˈdeɪndʒərəs]', russian: 'Опасный' },
  { key: '51', english: 'Harmless', pronunciation: '[ˈhɑːmləs]', russian: 'Безвредный' },
  { key: '52', english: 'Creepy', pronunciation: '[ˈkriːpi]', russian: 'Жуткий' },
  { key: '53', english: 'Spooky', pronunciation: '[ˈspuːki]', russian: 'Жуткий/зловещий' },
  { key: '54', english: 'Brave', pronunciation: '[breɪv]', russian: 'Храбрый' },
  { key: '55', english: 'Fearless', pronunciation: '[ˈfɪələs]', russian: 'Бесстрашный' },
  { key: '56', english: 'Shy', pronunciation: '[ʃaɪ]', russian: 'Застенчивый' },
  { key: '57', english: '-----', pronunciation: '-----', russian: '-----' },
  
  // USEFUL PHRASES (ПОЛЕЗНЫЕ ФРАЗЫ)
  { key: '58', english: 'Useful phrases', pronunciation: 'Useful phrases', russian: 'Полезные фразы' },
  { key: '59', english: 'I am afraid of...', pronunciation: '[aɪ æm əˈfreɪd ɒv]', russian: 'Я боюсь...' },
  { key: '60', english: 'I am scared of...', pronunciation: '[aɪ æm skeəd ɒv]', russian: 'Я напуган...' },
  { key: '61', english: 'I am terrified of...', pronunciation: '[aɪ æm ˈterɪfaɪd ɒv]', russian: 'Я в ужасе от...' },
  { key: '62', english: 'I feel nervous when...', pronunciation: '[aɪ fiːl ˈnɜːvəs wen]', russian: 'Я нервничаю, когда...' },
  { key: '63', english: 'I get scared if...', pronunciation: '[aɪ ɡet skeəd ɪf]', russian: 'Я пугаюсь, если...' },
  { key: '64', english: 'My heart beats fast', pronunciation: '[maɪ hɑːt biːts fɑːst]', russian: 'Мое сердце быстро бьется' },
  { key: '65', english: 'I cant breathe', pronunciation: '[aɪ kɑːnt briːð]', russian: 'Я не могу дышать' },
  { key: '66', english: 'I want to run away', pronunciation: '[aɪ wɒnt tə rʌn əˈweɪ]', russian: 'Я хочу убежать' },
  { key: '67', english: 'Dont worry!', pronunciation: '[dəʊnt ˈwʌri]', russian: 'Не волнуйся!' },
  { key: '68', english: 'Calm down!', pronunciation: '[kɑːm daʊn]', russian: 'Успокойся!' },
  { key: '69', english: '-----', pronunciation: '-----', russian: '-----' },
  
  // COMPARISON PHRASES (ФРАЗЫ ДЛЯ СРАВНЕНИЯ)
  { key: '70', english: 'Comparison', pronunciation: 'Comparison', russian: 'Сравнение' },
  { key: '71', english: 'More afraid of... than...', pronunciation: '[mɔːr əˈfreɪd ɒv ... ðæn]', russian: 'Более напуган... чем...' },
  { key: '72', english: 'Less scared of... than...', pronunciation: '[les skeəd ɒv ... ðæn]', russian: 'Менее напуган... чем...' },
  { key: '73', english: 'As scared as...', pronunciation: '[æz skeəd æz]', russian: 'Так же напуган, как...' },
  { key: '74', english: 'The most frightening', pronunciation: '[ðə məʊst ˈfraɪtnɪŋ]', russian: 'Самый пугающий' },
  { key: '75', english: 'Much more afraid', pronunciation: '[mʌtʃ mɔːr əˈfreɪd]', russian: 'Гораздо более испуган' },
];