export const allTravel = [
  { key: "1", english: "Airport", pronunciation: "/ˈɛəpɔːt/", russian: "Аэропорт" },
  { key: "2", english: "Flight", pronunciation: "/flaɪt/", russian: "Рейс, полет" },
  { key: "3", english: "Ticket", pronunciation: "/ˈtɪkɪt/", russian: "Билет" },
  { key: "4", english: "Luggage", pronunciation: "/ˈlʌɡɪdʒ/", russian: "Багаж" },
  { key: "5", english: "Suitcase", pronunciation: "/ˈsuːtkeɪs/", russian: "Чемодан" },
  { key: "6", english: "Passport", pronunciation: "/ˈpɑːspɔːt/", russian: "Паспорт" },
  { key: "7", english: "Baggage claim", pronunciation: "/ˈbæɡɪdʒ kleɪm/", russian: "Место получения багажа" },
  { key: "8", english: "Hotel", pronunciation: "/həʊˈtɛl/", russian: "Отель" },
  { key: "9", english: "Reservation", pronunciation: "/ˌrɛzəˈveɪʃən/", russian: "Бронирование" },
  { key: "10", english: "Check-in", pronunciation: "/ˈtʃɛk ɪn/", russian: "Регистрация" },
  { key: "11", english: "Boarding pass", pronunciation: "/ˈbɔːdɪŋ pɑːs/", russian: "Посадочный талон" },
  { key: "12", english: "Security check", pronunciation: "/sɪˈkjʊərɪti tʃɛk/", russian: "Контроль безопасности" },
  { key: "13", english: "Customs", pronunciation: "/ˈkʌstəmz/", russian: "Таможня" },
  { key: "14", english: "Travel agent", pronunciation: "/ˈtrævl ˈeɪdʒənt/", russian: "Туристический агент" },
  { key: "15", english: "Tourist", pronunciation: "/ˈtʊərɪst/", russian: "Турист" },
  { key: "16", english: "Map", pronunciation: "/mæp/", russian: "Карта" },
  { key: "17", english: "Destination", pronunciation: "/ˌdɛstɪˈneɪʃən/", russian: "Место назначения" },
  { key: "18", english: "Excursion", pronunciation: "/ɪkˈskɜːʃən/", russian: "Экскурсия" },
  { key: "19", english: "Guide", pronunciation: "/ɡaɪd/", russian: "Гид" },
  { key: "20", english: "Taxi", pronunciation: "/ˈtæksi/", russian: "Такси" },
  { key: "21", english: "Bus stop", pronunciation: "/bʌs stɒp/", russian: "Автобусная остановка" },
  { key: "22", english: "Train station", pronunciation: "/treɪn ˈsteɪʃən/", russian: "Вокзал" },
  { key: "23", english: "Board", pronunciation: "/bɔːd/", russian: "Садиться (на транспорт), борт" },
  { key: "24", english: "Journey", pronunciation: "/ˈdʒɜːni/", russian: "Путешествие" },
  { key: "25", english: "Stay", pronunciation: "/steɪ/", russian: "Пребывание, остаться" },
  { key: "26", english: "Tour", pronunciation: "/tʊə/", russian: "Тур, экскурсия" },
  { key: "27", english: "Itinerary", pronunciation: "/aɪˈtɪnəˌrɛri/", russian: "Маршрут" },
  { key: "28", english: "Vacation", pronunciation: "/veɪˈkeɪʃən/", russian: "Каникулы, отпуск" },
  { key: "29", english: "Trip", pronunciation: "/trɪp/", russian: "Поездка" },
  { key: "30", english: "Sightseeing", pronunciation: "/ˈsaɪtˌsiːɪŋ/", russian: "Осмотр достопримечательностей" },
  { key: "31", english: "Scenery", pronunciation: "/ˈsiːnəri/", russian: "Пейзаж" },
  { key: "32", english: "Adventure", pronunciation: "/ədˈvɛntʃər/", russian: "Приключение" },
  { key: "33", english: "Exciting", pronunciation: "/ɪkˈsaɪtɪŋ/", russian: "Захватывающий" },
  { key: "34", english: "Relax", pronunciation: "/rɪˈlæks/", russian: "Расслабляться" },
  { key: "35", english: "Beach", pronunciation: "/biːtʃ/", russian: "Пляж" },
  { key: "36", english: "Mountain", pronunciation: "/ˈmaʊntən/", russian: "Гора" },
  { key: "37", english: "Visa", pronunciation: "/ˈviːzə/", russian: "Виза" },
  { key: "38", english: "Travel insurance", pronunciation: "/ˈtrævl ɪnˈʃʊərəns/", russian: "Туристическая страховка" },
  { key: "39", english: "Adventurous", pronunciation: "/ədˈvɛntʃərəs/", russian: "Любящий приключения" },
  { key: "40", english: "Backpacker", pronunciation: "/ˈbækˌpækər/", russian: "Пешеходный турист" },
  { key: "41", english: "Cruise", pronunciation: "/kruːz/", russian: "Круиз" },
  { key: "42", english: "Accommodation", pronunciation: "/əˌkɒməˈdeɪʃən/", russian: "Проживание" },
  { key: "43", english: "Hotel room", pronunciation: "/həʊˈtɛl ruːm/", russian: "Номер в отеле" },
  { key: "44", english: "Tourist attraction", pronunciation: "/ˈtʊərɪst əˈtrækʃən/", russian: "Туристическая достопримечательность" },
  { key: "45", english: "Travel guide", pronunciation: "/ˈtrævl ɡaɪd/", russian: "Путеводитель" },
  { key: "46", english: "Hostel", pronunciation: "/ˈhɒstəl/", russian: "Хостел" },
  { key: "47", english: "Jet lag", pronunciation: "/ˈdʒɛt læɡ/", russian: "Джит-лаг (синдром смены часовых поясов)" },
  { key: "48", english: "Delay", pronunciation: "/dɪˈleɪ/", russian: "Задержка" },
  { key: "49", english: "Reservation", pronunciation: "/ˌrɛzəˈveɪʃən/", russian: "Бронирование" },
  { key: "50", english: "Cancellation", pronunciation: "/ˌkænsəˈleɪʃən/", russian: "Отмена" }
];

export const travel_01 = [
  { key: '1', english: 'Hello! I need a ticket to London, please.', russian: 'Здравствуйте! Мне нужен билет в Лондон, пожалуйста.' },
  { key: '2', english: 'One-way or round-trip?', russian: 'В одну сторону или туда и обратно?' },
  { key: '3', english: 'One-way, please.', russian: 'В одну сторону, пожалуйста.' },
  { key: '4', english: 'First class or economy?', russian: 'Первый класс или эконом?' },
  { key: '5', english: 'Economy.', russian: 'Эконом.' },
  { key: '6', english: 'That’s 15 pounds.', russian: 'Это 15 фунтов.' },
  { key: '7', english: 'Here you go.', russian: 'Вот, пожалуйста.' },
  { key: '8', english: 'Thank you. Here is your ticket. The train leaves at 10:30.', russian: 'Спасибо. Вот ваш билет. Поезд отправляется в 10:30.' },
  { key: '9', english: 'Where is platform 4?', russian: 'Где платформа 4?' },
  { key: '10', english: 'It’s to your left.', russian: 'Она слева от вас.' },
  { key: '11', english: 'Thanks a lot!', russian: 'Большое спасибо!' },
  { key: '12', english: 'You’re welcome! Have a good trip!', russian: 'Пожалуйста! Хорошего пути!' },
]

export const travel_02 = [
  { key: '1', english: 'Hello! Where is the check-in desk?', russian: 'Здравствуйте! Где стойка регистрации?' },
  { key: '2', english: 'Hello! The check-in desk is over there.', russian: 'Здравствуйте! Стойка регистрации там.' },
  { key: '3', english: 'Thank you.', russian: 'Спасибо.' },
  { key: '4', english: 'You’re welcome. May I see your passport and ticket, please?', russian: 'Пожалуйста. Могу я увидеть ваш паспорт и билет?' },
  { key: '5', english: 'Yes, here you are.', russian: 'Да, вот они.' },
  { key: '6', english: 'Thank you. Do you have any luggage?', russian: 'Спасибо. У вас есть багаж?' },
  { key: '7', english: 'Yes, I have one suitcase.', russian: 'Да, у меня один чемодан.' },
  { key: '8', english: 'Please put it on the scale.', russian: 'Пожалуйста, положите его на весы.' },
  { key: '9', english: 'Okay.', russian: 'Хорошо.' },
  { key: '10', english: 'Great. Here is your boarding pass. Your gate is A12.', russian: 'Отлично. Вот ваш посадочный талон. Ваш выход A12.' },
  { key: '11', english: 'Thank you very much!', russian: 'Большое спасибо!' },
  { key: '12', english: 'Have a nice flight!', russian: 'Хорошего полета!' },
  { key: '13', english: 'Thanks! Bye!', russian: 'Спасибо! Пока!' },
]

export const travel_03 = [
  { key: '1', english: 'Excuse me, is this seat 14B?', russian: 'Извините, это место 14B?' },
  { key: '2', english: 'Yes, it is.', russian: 'Да, это оно.' },
  { key: '3', english: 'Great! Thank you.', russian: 'Отлично! Спасибо.' },
  { key: '4', english: 'You’re welcome.', russian: 'Пожалуйста.' },
  { key: '5', english: 'How long is the flight?', russian: 'Сколько длится полет?' },
  { key: '6', english: 'About two hours.', russian: 'Примерно два часа.' },
  { key: '7', english: 'That’s not too bad.', russian: 'Это не так уж и плохо.' },
  { key: '8', english: 'Yes, it’s a short flight.', russian: 'Да, это короткий рейс.' },
  { key: '9', english: 'Do they serve food on the plane?', russian: 'На борту дают еду?' },
  { key: '10', english: 'Yes, but only snacks and drinks.', russian: 'Да, но только закуски и напитки.' },
  { key: '11', english: 'Good to know. Thanks!', russian: 'Хорошо знать. Спасибо!' },
]

export const travel_05 = [
  { key: '1', english: 'Hello! Can you help me?', russian: 'Здравствуйте! Вы можете мне помочь?' },
  { key: '2', english: 'Of course! How can I help you?', russian: 'Конечно! Чем могу помочь?' },
  { key: '3', english: 'I want to visit the beach. How can I get there?', russian: 'Я хочу посетить пляж. Как мне туда добраться?' },
  { key: '4', english: 'You can take a bus or a taxi.', russian: 'Вы можете поехать на автобусе или такси.' },
  { key: '5', english: 'Where is the bus stop?', russian: 'Где остановка автобуса?' },
  { key: '6', english: 'It’s right outside, next to the coffee shop.', russian: 'Она прямо у выхода, рядом с кофейней.' },
  { key: '7', english: 'Great! How much is the bus ticket?', russian: 'Отлично! Сколько стоит билет на автобус?' },
  { key: '8', english: 'It’s 2 dollars.', russian: '2 доллара.' },
  { key: '9', english: 'Thank you! And what can I see at the beach?', russian: 'Спасибо! Что я могу увидеть на пляже?' },
  { key: '10', english: 'You can swim, relax, and try some local food.', russian: 'Вы можете плавать, отдыхать и попробовать местную еду.' },
  { key: '11', english: 'Sounds nice! Thanks for your help.', russian: 'Звучит здорово! Спасибо за помощь.' },
  { key: '12', english: 'You’re welcome! Enjoy your day!', russian: 'Пожалуйста! Хорошего дня!' },
]

export const travel_06 = [
  { key: '1', english: 'Excuse me, where is the bus to the city center?', russian: 'Извините, где автобус в центр города?' },
  { key: '2', english: 'It’s bus number 5.', russian: 'Это автобус номер 5.' },
  { key: '3', english: 'Where is the bus stop?', russian: 'Где остановка автобуса?' },
  { key: '4', english: 'Over there, near the café.', russian: 'Там, рядом с кафе.' },
  { key: '5', english: 'How much is the ticket?', russian: 'Сколько стоит билет?' },
  { key: '6', english: 'It’s 3 dollars.', russian: '3 доллара.' },
  { key: '7', english: 'Thank you! When does the bus leave?', russian: 'Спасибо! Когда отправляется автобус?' },
  { key: '8', english: 'In 15 minutes.', russian: 'Через 15 минут.' },
  { key: '9', english: 'Great! Thanks for your help.', russian: 'Отлично! Спасибо за помощь.' },
  { key: '10', english: 'You’re welcome!', russian: 'Пожалуйста!' },
]

export const travel_07 = [
  { key: '1', english: 'Excuse me, where can I buy a train ticket?', russian: 'Извините, где я могу купить билет на поезд?' },
  { key: '2', english: 'At the ticket office or the machine.', russian: 'В кассе или в автомате.' },
  { key: '3', english: 'Can I pay by card?', russian: 'Можно оплатить картой?' },
  { key: '4', english: 'Yes, of course.', russian: 'Да, конечно.' },
  { key: '5', english: 'Good. How long does it take to get to Brighton?', russian: 'Хорошо. Сколько времени занимает путь до Брайтона?' },
  { key: '6', english: 'About one hour.', russian: 'Примерно один час.' },
  { key: '7', english: 'And how much is a return ticket?', russian: 'А сколько стоит билет туда и обратно?' },
  { key: '8', english: 'It’s 20 pounds.', russian: '20 фунтов.' },
  { key: '9', english: 'Thank you! Where is platform 3?', russian: 'Спасибо! Где платформа 3?' },
  { key: '10', english: 'Just follow the signs. It’s to the right.', russian: 'Просто следуйте по указателям. Она справа.' },
  { key: '11', english: 'Thanks a lot!', russian: 'Большое спасибо!' },
]

export const travel_08 = [
  { key: '1', english: 'Good morning! Can you recommend some places to visit?', russian: 'Доброе утро! Вы можете порекомендовать места для посещения?' },
  { key: '2', english: 'Of course! Are you interested in museums, parks, or shopping?', russian: 'Конечно! Вас интересуют музеи, парки или шоппинг?' },
  { key: '3', english: 'I like museums and parks.', russian: 'Мне нравятся музеи и парки.' },
  { key: '4', english: 'You should visit the City Museum and Green Park. Both are very popular.', russian: 'Вам стоит посетить Городской музей и Зеленый парк. Оба очень популярны.' },
  { key: '5', english: 'How do I get there?', russian: 'Как мне туда добраться?' },
  { key: '6', english: 'The museum is a 10-minute walk from here, and the park is a bit further, but you can take bus 12.', russian: 'Музей в 10 минутах ходьбы отсюда, а парк немного дальше, но вы можете поехать на автобусе 12.' },
  { key: '7', english: 'Great! Is there a map I can take?', russian: 'Отлично! Есть ли у вас карта, которую я могу взять?' },
  { key: '8', english: 'Yes, here you go.', russian: 'Да, вот.' },
  { key: '9', english: 'Thank you so much!', russian: 'Большое спасибо!' },
]

export const travel_09 = [
  { key: '1', english: 'Excuse me! Can you help me find the Central Market?', russian: 'Извините! Вы можете помочь мне найти Центральный рынок?' },
  { key: '2', english: 'Sure! It’s not far from here. Go straight ahead and turn right at the traffic light.', russian: 'Конечно! Это недалеко отсюда. Идите прямо и поверните направо на светофоре.' },
  { key: '3', english: 'Okay, straight ahead and then right.', russian: 'Хорошо, прямо и затем направо.' },
  { key: '4', english: 'Yes. The market will be on your left, next to the big supermarket.', russian: 'Да. Рынок будет слева от вас, рядом с большим супермаркетом.' },
  { key: '5', english: 'How long does it take to walk there?', russian: 'Сколько времени займет, чтобы дойти туда?' },
  { key: '6', english: 'About 15 minutes.', russian: 'Примерно 15 минут.' },
  { key: '7', english: 'Perfect! Thanks a lot!', russian: 'Отлично! Большое спасибо!' },
  { key: '8', english: 'You’re welcome! Enjoy your visit!', russian: 'Пожалуйста! Наслаждайтесь визитом!' },
]

export const travel_10 = [
  { key: '1', english: 'Excuse me, where can I buy a ticket for the metro?', russian: 'Извините, где я могу купить билет на метро?' },
  { key: '2', english: 'You can buy a ticket at the ticket machine or at the counter.', russian: 'Вы можете купить билет в автомате или в кассе.' },
  { key: '3', english: 'How much is a single ticket?', russian: 'Сколько стоит одноразовый билет?' },
  { key: '4', english: 'A single ticket costs 1.50 pounds.', russian: 'Одноразовый билет стоит 1.50 фунта.' },
  { key: '5', english: 'Can I pay with a card?', russian: 'Можно ли оплатить картой?' },
  { key: '6', english: 'Yes, you can pay with a card or cash.', russian: 'Да, можно оплатить картой или наличными.' },
  { key: '7', english: 'Where is the metro entrance?', russian: 'Где вход в метро?' },
  { key: '8', english: 'The entrance is just over there, next to the bus stop.', russian: 'Вход прямо там, рядом с автобусной остановкой.' },
  { key: '9', english: 'Thank you! How many stops to the city center?', russian: 'Спасибо! Сколько остановок до центра города?' },
  { key: '10', english: 'There are 5 stops to the city center.', russian: 'До центра города 5 остановок.' },
  { key: '11', english: 'Great! Thanks for your help.', russian: 'Отлично! Спасибо за помощь.' },
  { key: '12', english: 'You’re welcome! Have a good trip!', russian: 'Пожалуйста! Хорошего пути!' },
]