export const householdObjects = [
  { key: '1', english: 'Table', pronunciation: '[ˈteɪbəl]', russian: 'Стол' },
  { key: '2', english: 'Chair', pronunciation: '[tʃeə]', russian: 'Стул' },
  { key: '3', english: 'Armchair', pronunciation: '[ˈɑːmtʃeə]', russian: 'Кресло' },
  { key: '4', english: 'Sofa', pronunciation: '[ˈsəʊfə]', russian: 'Диван' },
  { key: '5', english: 'Bed', pronunciation: '[bed]', russian: 'Кровать' },
  { key: '6', english: 'Desk', pronunciation: '[desk]', russian: 'Письменный стол' },
  { key: '7', english: 'Wardrobe', pronunciation: '[ˈwɔːdrəʊb]', russian: 'Шкаф для одежды' },
  { key: '8', english: 'Cupboard', pronunciation: '[ˈkʌbəd]', russian: 'Шкаф' },
  { key: '9', english: 'Drawer', pronunciation: '[drɔː]', russian: 'Ящик' },
  { key: '10', english: 'Shelf', pronunciation: '[ʃelf]', russian: 'Полка' },
  { key: '11', english: 'Mirror', pronunciation: '[ˈmɪrə]', russian: 'Зеркало' },
  { key: '12', english: 'Carpet', pronunciation: '[ˈkɑːpɪt]', russian: 'Ковёр' },
  { key: '13', english: 'Curtains', pronunciation: '[ˈkɜːtənz]', russian: 'Шторы' },
  { key: '14', english: 'Lamp', pronunciation: '[læmp]', russian: 'Лампа' },
  { key: '15', english: 'Light', pronunciation: '[laɪt]', russian: 'Свет / лампа' },
  { key: '16', english: 'Clock', pronunciation: '[klɒk]', russian: 'Часы' },
  { key: '17', english: 'Door', pronunciation: '[dɔː]', russian: 'Дверь' },
  { key: '18', english: 'Window', pronunciation: '[ˈwɪndəʊ]', russian: 'Окно' },
  { key: '19', english: 'Key', pronunciation: '[kiː]', russian: 'Ключ' },
  { key: '20', english: 'Lock', pronunciation: '[lɒk]', russian: 'Замок' },
  { key: '21', english: 'Fridge', pronunciation: '[frɪdʒ]', russian: 'Холодильник' },
  { key: '22', english: 'Cooker', pronunciation: '[ˈkʊkə]', russian: 'Плита' },
  { key: '23', english: 'Oven', pronunciation: '[ˈʌvən]', russian: 'Духовка' },
  { key: '24', english: 'Microwave', pronunciation: '[ˈmaɪkrəweɪv]', russian: 'Микроволновка' },
  { key: '25', english: 'Dishwasher', pronunciation: '[ˈdɪʃˌwɒʃə]', russian: 'Посудомоечная машина' },
  { key: '26', english: 'Washing machine', pronunciation: '[ˈwɒʃɪŋ məˌʃiːn]', russian: 'Стиральная машина' },
  { key: '27', english: 'Kettle', pronunciation: '[ˈketl]', russian: 'Чайник' },
  { key: '28', english: 'Toaster', pronunciation: '[ˈtəʊstə]', russian: 'Тостер' },
  { key: '29', english: 'Iron', pronunciation: '[ˈaɪən]', russian: 'Утюг' },
  { key: '30', english: 'Vacuum cleaner', pronunciation: '[ˈvækjuːm ˌkliːnə]', russian: 'Пылесос' },
  { key: '31', english: 'Television', pronunciation: '[ˈtelɪˌvɪʒən]', russian: 'Телевизор' },
  { key: '32', english: 'Remote control', pronunciation: '[rɪˌməʊt kənˈtrəʊl]', russian: 'Пульт' },
  { key: '33', english: 'Computer', pronunciation: '[kəmˈpjuːtə]', russian: 'Компьютер' },
  { key: '34', english: 'Laptop', pronunciation: '[ˈlæptɒp]', russian: 'Ноутбук' },
  { key: '35', english: 'Phone', pronunciation: '[fəʊn]', russian: 'Телефон' },
  { key: '36', english: 'Radio', pronunciation: '[ˈreɪdiəʊ]', russian: 'Радио' },
  { key: '37', english: 'Cup', pronunciation: '[kʌp]', russian: 'Чашка' },
  { key: '38', english: 'Glass', pronunciation: '[ɡlɑːs]', russian: 'Стакан' },
  { key: '39', english: 'Bottle', pronunciation: '[ˈbɒtl]', russian: 'Бутылка' },
  { key: '40', english: 'Plate', pronunciation: '[pleɪt]', russian: 'Тарелка' },
  { key: '41', english: 'Bowl', pronunciation: '[bəʊl]', russian: 'Миска' },
  { key: '42', english: 'Knife', pronunciation: '[naɪf]', russian: 'Нож' },
  { key: '43', english: 'Fork', pronunciation: '[fɔːk]', russian: 'Вилка' },
  { key: '44', english: 'Spoon', pronunciation: '[spuːn]', russian: 'Ложка' },
  { key: '45', english: 'Pan', pronunciation: '[pæn]', russian: 'Сковорода' },
  { key: '46', english: 'Pot', pronunciation: '[pɒt]', russian: 'Кастрюля' },
  { key: '47', english: 'Towel', pronunciation: '[ˈtaʊəl]', russian: 'Полотенце' },
  { key: '48', english: 'Soap', pronunciation: '[səʊp]', russian: 'Мыло' },
  { key: '49', english: 'Toothbrush', pronunciation: '[ˈtuːθbrʌʃ]', russian: 'Зубная щётка' },
  { key: '50', english: 'Toothpaste', pronunciation: '[ˈtuːθpeɪst]', russian: 'Зубная паста' },
  { key: '51', english: 'Shampoo', pronunciation: '[ʃæmˈpuː]', russian: 'Шампунь' },
  { key: '52', english: 'Pillow', pronunciation: '[ˈpɪləʊ]', russian: 'Подушка' },
  { key: '53', english: 'Blanket', pronunciation: '[ˈblæŋkɪt]', russian: 'Одеяло' },
  { key: '54', english: 'Sheet', pronunciation: '[ʃiːt]', russian: 'Простыня' },
  { key: '55', english: 'Bin', pronunciation: '[bɪn]', russian: 'Мусорное ведро' },
  { key: '56', english: 'Bucket', pronunciation: '[ˈbʌkɪt]', russian: 'Ведро' },
  { key: '57', english: 'Brush', pronunciation: '[brʌʃ]', russian: 'Щётка' },
  { key: '58', english: 'Mop', pronunciation: '[mɒp]', russian: 'Швабра' },
  { key: '59', english: 'Ironing board', pronunciation: '[ˈaɪənɪŋ bɔːd]', russian: 'Гладильная доска' },
  { key: '60', english: 'Hairdryer', pronunciation: '[ˈheədraɪə]', russian: 'Фен' },
];
